DEBUG 2024-09-17 15:43:30.338 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-17 15:43:30.339 UTC: 	 Running on: Linux lxplus999.cern.ch 5.14.0-427.28.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jul 19 14:40:47 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-09-17 15:43:30.339 UTC: 	 Executing command: 'submit'
DEBUG 2024-09-17 15:43:30.339 UTC: 	 Found CRAB cache file /afs/cern.ch/user/f/fnenna/.crab3
ERROR 2024-09-17 15:43:30.342 UTC: 	 CRAB configuration file crab_DsPhiPi_reco2023_RunC-v1_stream0_cfg.py not found.
ERROR 2024-09-17 15:43:30.342 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 325, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 53, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
CRABClient.ClientExceptions.ConfigurationException: CRAB configuration file crab_DsPhiPi_reco2023_RunC-v1_stream0_cfg.py not found.
INFO 2024-09-17 15:43:30.351 UTC: 	 Log file is /eos/home-f/fnenna/tau3mu/CMSSW_14_0_12/src/CrabSubmission/Data_2024/SkimPhiPi/reco2024_RunC/crab.log
DEBUG 2024-09-17 15:43:38.195 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-17 15:43:38.195 UTC: 	 Running on: Linux lxplus999.cern.ch 5.14.0-427.28.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jul 19 14:40:47 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-09-17 15:43:38.195 UTC: 	 Executing command: 'submit'
DEBUG 2024-09-17 15:43:38.196 UTC: 	 Found CRAB cache file /afs/cern.ch/user/f/fnenna/.crab3
ERROR 2024-09-17 15:43:38.198 UTC: 	 CRAB configuration file crab_DsPhiPi_reco2023_RunC-v1_stream1_cfg.py not found.
ERROR 2024-09-17 15:43:38.198 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 325, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 53, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
CRABClient.ClientExceptions.ConfigurationException: CRAB configuration file crab_DsPhiPi_reco2023_RunC-v1_stream1_cfg.py not found.
INFO 2024-09-17 15:43:38.209 UTC: 	 Log file is /eos/home-f/fnenna/tau3mu/CMSSW_14_0_12/src/CrabSubmission/Data_2024/SkimPhiPi/reco2024_RunC/crab.log
DEBUG 2024-09-17 15:43:46.196 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-17 15:43:46.197 UTC: 	 Running on: Linux lxplus999.cern.ch 5.14.0-427.28.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jul 19 14:40:47 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-09-17 15:43:46.197 UTC: 	 Executing command: 'submit'
DEBUG 2024-09-17 15:43:46.197 UTC: 	 Found CRAB cache file /afs/cern.ch/user/f/fnenna/.crab3
ERROR 2024-09-17 15:43:46.200 UTC: 	 CRAB configuration file crab_DsPhiPi_reco2023_RunC-v1_stream2_cfg.py not found.
ERROR 2024-09-17 15:43:46.201 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 325, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 53, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
CRABClient.ClientExceptions.ConfigurationException: CRAB configuration file crab_DsPhiPi_reco2023_RunC-v1_stream2_cfg.py not found.
INFO 2024-09-17 15:43:46.208 UTC: 	 Log file is /eos/home-f/fnenna/tau3mu/CMSSW_14_0_12/src/CrabSubmission/Data_2024/SkimPhiPi/reco2024_RunC/crab.log
DEBUG 2024-09-18 09:04:39.572 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-18 09:04:39.572 UTC: 	 Running on: Linux lxplus988.cern.ch 5.14.0-427.35.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Aug 30 15:47:10 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-09-18 09:04:39.572 UTC: 	 Executing command: 'status'
DEBUG 2024-09-18 09:04:39.573 UTC: 	 Found CRAB cache file /afs/cern.ch/user/f/fnenna/.crab3
ERROR 2024-09-18 09:04:39.574 UTC: 	 Error: crab_projects/crab_SkimDsPhiPi_2024eraC_stream2 is not a valid CRAB project directory.
ERROR 2024-09-18 09:04:39.574 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 680, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_SkimDsPhiPi_2024eraC_stream2 is not a valid CRAB project directory.
INFO 2024-09-18 09:04:39.580 UTC: 	 Log file is /eos/home-f/fnenna/tau3mu/CMSSW_14_0_12/src/CrabSubmission/Data_2024/SkimPhiPi/reco2024_RunC/crab.log
